site_name: Todo
theme:
  name: material
  features:
    - navigation.path
    - toc.follow
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

repo_url: https://github.com/gckopper/swe-2-todo
plugins:
  - search

markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format